// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlyFling.Api.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "deployed")]
    public partial class DeployedAuthenticatedAPIAndUIJourneyFeature : object, global::Xunit.IClassFixture<DeployedAuthenticatedAPIAndUIJourneyFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "deployed"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Deployed authenticated API and UI journey", "  The release pipeline should validate the signed-in creator flow on the deployed" +
                " app.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DeployedAuthenticatedJourney.feature"
#line hidden
        
        public DeployedAuthenticatedAPIAndUIJourneyFeature(DeployedAuthenticatedAPIAndUIJourneyFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DeployedAuthenticatedJourney.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A signed-in creator can update profile, create a collection, and stage an upload")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Deployed authenticated API and UI journey")]
        [global::Xunit.TraitAttribute("Description", "A signed-in creator can update profile, create a collection, and stage an upload")]
        public async global::System.Threading.Tasks.Task ASigned_InCreatorCanUpdateProfileCreateACollectionAndStageAnUpload()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A signed-in creator can update profile, create a collection, and stage an upload", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync("I sign in on the \"stable\" ring as \"bdd-journey@example.com\" using device \"BDD Jou" +
                        "rney Browser\" and store it as \"journey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("I send a \"POST\" request to \"/account/profile\" on the \"stable\" ring as \"journey\" w" +
                        "ith JSON:", @"{
  ""displayName"": ""BDD Journey Creator"",
  ""bio"": ""Deployed journey coverage."",
  ""avatarUrl"": ""https://example.com/avatar.jpg"",
  ""preferences"": {
    ""contentTags"": [""journey"", ""bdd""],
    ""collaborationInterests"": [""creator-tools""],
    ""languages"": [""en""]
  },
  ""privacy"": {
    ""profileVisibility"": ""public"",
    ""discoverable"": true,
    ""showActivity"": true,
    ""allowDirectMessages"": false
  },
  ""contact"": {
    ""supportEmail"": ""bdd-journey@example.com"",
    ""emailOptIn"": true,
    ""marketingOptIn"": false
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
    await testRunner.AndAsync("the response JSON at \"profile.displayName\" should equal \"BDD Journey Creator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/collections\" on the \"stable\" ring as \"journey\"" +
                        " with JSON:", "{\r\n  \"folderName\": \"bdd-journey-folder\",\r\n  \"title\": \"BDD Journey Collection\",\r\n " +
                        " \"description\": \"Deployed collection coverage.\",\r\n  \"visibility\": \"private\",\r\n  " +
                        "\"publishState\": \"draft\",\r\n  \"priceMinor\": 1200,\r\n  \"currency\": \"GBP\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
    await testRunner.AndAsync("I save the response JSON at \"collection.id\" as \"journeyCollectionId\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/uploads/intake\" on the \"stable\" ring as \"journ" +
                        "ey\" with JSON:", @"{
  ""collectionId"": ""{{journeyCollectionId}}"",
  ""title"": ""BDD Journey Upload"",
  ""description"": ""Deployed upload intake coverage."",
  ""fileName"": ""journey-image.jpg"",
  ""contentType"": ""image/jpeg"",
  ""mediaType"": ""image"",
  ""ageRating"": ""general"",
  ""fileSizeBytes"": 2048,
  ""priceMinor"": 1200,
  ""currency"": ""GBP"",
  ""publishState"": ""draft"",
  ""encodingProfile"": {
    ""qualityProfile"": ""balanced"",
    ""bitrateProfile"": ""standard""
  },
  ""consent"": {
    ""performerCount"": 1,
    ""allAdultsConfirmed"": true,
    ""rightsConfirmed"": true,
    ""consentCapturedAt"": ""2026-05-01T10:15:00Z"",
    ""consentDocumentName"": ""bdd-journey-consent"",
    ""recordRetentionYears"": 7,
    ""notes"": ""Deployed journey consent coverage.""
  },
  ""policy"": {
    ""folderName"": ""bdd-journey-folder"",
    ""documentName"": ""bdd-journey-consent"",
    ""termsSummary"": ""Adult-only upload with documented rights."",
    ""pricingSummary"": ""Journey upload stays draft until moderation."",
    ""additionalNotes"": ""Release validation artifact.""
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
    await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.AndAsync("the response JSON at \"mediaItem.uploadStatus\" should equal \"pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
    await testRunner.AndAsync("the response JSON at \"upload.mode\" should equal \"memory\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
    await testRunner.AndAsync("the response JSON at \"workItems[0].jobType\" should equal \"metadata-scrub\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DeployedAuthenticatedAPIAndUIJourneyFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DeployedAuthenticatedAPIAndUIJourneyFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
