// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlyFling.Api.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MediaRenderingAndPublishContractsFeature : object, global::Xunit.IClassFixture<MediaRenderingAndPublishContractsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Media rendering and publish contracts", "  Media endpoints should expose stable rendering metadata and publish state trans" +
                "itions.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MediaContracts.feature"
#line hidden
        
        public MediaRenderingAndPublishContractsFeature(MediaRenderingAndPublishContractsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MediaContracts.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Media collections expose rendering data and publish updates")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Media rendering and publish contracts")]
        [global::Xunit.TraitAttribute("Description", "Media collections expose rendering data and publish updates")]
        public async global::System.Threading.Tasks.Task MediaCollectionsExposeRenderingDataAndPublishUpdates()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Media collections expose rendering data and publish updates", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("I sign in on the \"stable\" ring as \"anna@example.com\" using device \"BDD Anna Brows" +
                        "er\" and store it as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.WhenAsync("I send a \"GET\" request to \"/media/collections\" on the \"stable\" ring as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table8.AddRow(new string[] {
                            "id",
                            "collection-anna-editorial"});
                table8.AddRow(new string[] {
                            "publishState",
                            "published"});
                table8.AddRow(new string[] {
                            "soldCount",
                            "20"});
                table8.AddRow(new string[] {
                            "earnedMinor",
                            "26100"});
#line 9
    await testRunner.AndAsync("the response JSON array at \"collections\" should contain an object with:", ((string)(null)), table8, "And ");
#line hidden
#line 16
    await testRunner.WhenAsync("I send a \"GET\" request to \"/media/collections/collection-anna-editorial/items\" on" +
                        " the \"stable\" ring as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table9.AddRow(new string[] {
                            "id",
                            "media-anna-ready-1"});
                table9.AddRow(new string[] {
                            "mediaType",
                            "image"});
                table9.AddRow(new string[] {
                            "contentType",
                            "image/jpeg"});
                table9.AddRow(new string[] {
                            "fileName",
                            "image-a1b2c3.jpg"});
                table9.AddRow(new string[] {
                            "uploadStatus",
                            "ready"});
                table9.AddRow(new string[] {
                            "publishState",
                            "published"});
                table9.AddRow(new string[] {
                            "policyArtifact.id",
                            "policy-anna-editorial"});
#line 18
    await testRunner.AndAsync("the response JSON array at \"items\" should contain an object with:", ((string)(null)), table9, "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table10.AddRow(new string[] {
                            "id",
                            "media-anna-processing-1"});
                table10.AddRow(new string[] {
                            "uploadStatus",
                            "processing"});
                table10.AddRow(new string[] {
                            "preview.status",
                            "queued"});
                table10.AddRow(new string[] {
                            "publishState",
                            "draft"});
#line 27
    await testRunner.AndAsync("the response JSON array at \"items\" should contain an object with:", ((string)(null)), table10, "And ");
#line hidden
#line 34
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/items/update\" on the \"stable\" ring as \"anna\" w" +
                        "ith JSON:", "{\r\n  \"mediaItemId\": \"media-anna-processing-1\",\r\n  \"title\": \"Behind The Scenes Ree" +
                        "l\",\r\n  \"description\": \"Published through BDD contract coverage.\",\r\n  \"priceMinor" +
                        "\": 1200,\r\n  \"currency\": \"GBP\",\r\n  \"publishState\": \"published\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
    await testRunner.AndAsync("the response JSON at \"mediaItem.publishState\" should equal \"published\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.WhenAsync("I send a \"GET\" request to \"/media/collections/collection-anna-editorial/items\" on" +
                        " the \"stable\" ring as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table11.AddRow(new string[] {
                            "id",
                            "media-anna-processing-1"});
                table11.AddRow(new string[] {
                            "publishState",
                            "published"});
#line 50
    await testRunner.AndAsync("the response JSON array at \"items\" should contain an object with:", ((string)(null)), table11, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MediaRenderingAndPublishContractsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MediaRenderingAndPublishContractsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
