// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlyFling.Api.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class IntegrationAndModuleManagementSafeguardsFeature : object, global::Xunit.IClassFixture<IntegrationAndModuleManagementSafeguardsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Integration and module management safeguards", "  Connector and module catalogs should stay guarded and age restricted.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ModuleManagement.feature"
#line hidden
        
        public IntegrationAndModuleManagementSafeguardsFeature(IntegrationAndModuleManagementSafeguardsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ModuleManagement.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Guarded modules stay template-only and age restrictions are enforced")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Integration and module management safeguards")]
        [global::Xunit.TraitAttribute("Description", "Guarded modules stay template-only and age restrictions are enforced")]
        public async global::System.Threading.Tasks.Task GuardedModulesStayTemplate_OnlyAndAgeRestrictionsAreEnforced()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Guarded modules stay template-only and age restrictions are enforced", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("I sign in on the \"stable\" ring as \"anna@example.com\" using device \"BDD Anna Modul" +
                        "es\" and store it as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
    await testRunner.AndAsync("I sign in on the \"stable\" ring as \"luca@example.com\" using device \"BDD Luca Modul" +
                        "es\" and store it as \"luca\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.WhenAsync("I send a \"GET\" request to \"/connectors/modules\" on the \"stable\" ring as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table13.AddRow(new string[] {
                            "id",
                            "onlyfans"});
                table13.AddRow(new string[] {
                            "status",
                            "template"});
#line 10
    await testRunner.AndAsync("the response JSON array at \"connectors\" should contain an object with:", ((string)(null)), table13, "And ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table14.AddRow(new string[] {
                            "id",
                            "adult-platform-readiness"});
                table14.AddRow(new string[] {
                            "eligibility.allowed",
                            "true"});
                table14.AddRow(new string[] {
                            "eligibility.requiresCanaryRing",
                            "true"});
                table14.AddRow(new string[] {
                            "eligibility.effectiveChannel",
                            "stable"});
#line 14
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table14, "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table15.AddRow(new string[] {
                            "id",
                            "adult-platform-preview"});
                table15.AddRow(new string[] {
                            "eligibility.allowed",
                            "false"});
                table15.AddRow(new string[] {
                            "eligibility.requiresPreviewEnrollment",
                            "true"});
                table15.AddRow(new string[] {
                            "eligibility.reason",
                            "preview-enrollment-required"});
#line 20
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table15, "And ");
#line hidden
#line 27
    await testRunner.WhenAsync("I send a \"GET\" request to \"/connectors/modules\" on the \"stable\" ring as \"luca\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table16.AddRow(new string[] {
                            "id",
                            "adult-platform-readiness"});
                table16.AddRow(new string[] {
                            "eligibility.allowed",
                            "false"});
                table16.AddRow(new string[] {
                            "eligibility.reason",
                            "account-age-restricted"});
#line 29
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table16, "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table17.AddRow(new string[] {
                            "id",
                            "creator-analytics"});
                table17.AddRow(new string[] {
                            "eligibility.allowed",
                            "true"});
                table17.AddRow(new string[] {
                            "eligibility.effectiveChannel",
                            "stable"});
#line 34
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table17, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IntegrationAndModuleManagementSafeguardsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IntegrationAndModuleManagementSafeguardsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
