// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlyFling.Api.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CommerceAndPaymentControlsFeature : object, global::Xunit.IClassFixture<CommerceAndPaymentControlsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Commerce and payment controls", "  Credits purchases, invoices, age restrictions, and admin plugin controls should" +
                " stay isolated and auditable.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentCommerce.feature"
#line hidden
        
        public CommerceAndPaymentControlsFeature(CommerceAndPaymentControlsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PaymentCommerce.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Adult purchase flow respects account settings and admin payment controls")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Commerce and payment controls")]
        [global::Xunit.TraitAttribute("Description", "Adult purchase flow respects account settings and admin payment controls")]
        public async global::System.Threading.Tasks.Task AdultPurchaseFlowRespectsAccountSettingsAndAdminPaymentControls()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Adult purchase flow respects account settings and admin payment controls", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("I sign in on the \"stable\" ring as \"admin@example.com\" using device \"BDD Admin Pay" +
                        "ments\" and store it as \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
    await testRunner.AndAsync("I sign in on the \"stable\" ring as \"zoe@example.com\" using device \"BDD Buyer Mobil" +
                        "e\" and store it as \"buyer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.WhenAsync("I send a \"GET\" request to \"/plugins/active\" on the \"stable\" ring as \"buyer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table17.AddRow(new string[] {
                            "id",
                            "stripe"});
                table17.AddRow(new string[] {
                            "enabled",
                            "true"});
                table17.AddRow(new string[] {
                            "category",
                            "payment"});
#line 10
    await testRunner.AndAsync("the response JSON array at \"plugins\" should contain an object with:", ((string)(null)), table17, "And ");
#line hidden
#line 16
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/items/purchase\" on the \"stable\" ring as \"buyer" +
                        "\" with JSON:", "{\r\n  \"mediaItemId\": \"media-anna-adult-1\",\r\n  \"paymentMethod\": \"credits\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("the response status should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
    await testRunner.AndAsync("the response JSON at \"error\" should equal \"adult-content-age-verification-require" +
                        "d\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.WhenAsync("I send a \"POST\" request to \"/admin/plugins/config\" on the \"stable\" ring as \"buyer" +
                        "\" with JSON:", @"{
  ""pluginId"": ""stripe"",
  ""purchaseBehavior"": {
    ""defaultPurchaseMethod"": ""stripeCheckout"",
    ""allowedPurchaseMethods"": [""stripeCheckout""],
    ""requireAgeVerificationForAdultContent"": true,
    ""allowEntertainmentLabeling"": true,
    ""minimumPurchaseMinor"": 100,
    ""maximumPurchaseMinor"": 250000
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
    await testRunner.ThenAsync("the response status should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.WhenAsync("I send a \"POST\" request to \"/account/settings\" on the \"stable\" ring as \"buyer\" wi" +
                        "th JSON:", @"{
  ""notifications"": {
    ""email"": true,
    ""push"": true,
    ""product"": true,
    ""payouts"": true,
    ""security"": true
  },
  ""deviceSync"": {
    ""enabled"": true
  },
  ""payoutPreferences"": {
    ""settlementCurrency"": ""GBP"",
    ""schedule"": ""manual"",
    ""methodStatus"": ""not-configured""
  },
  ""purchasePreferences"": {
    ""ageVerifiedAdult"": true,
    ""labelAsEntertainment"": true,
    ""entertainmentLabelValue"": ""Leisure content value""
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
    await testRunner.AndAsync("the response JSON at \"settings.purchasePreferences.ageVerifiedAdult\" should equal" +
                        " \"true\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.WhenAsync("I send a \"POST\" request to \"/admin/plugins/config\" on the \"stable\" ring as \"admin" +
                        "\" with JSON:", @"{
  ""pluginId"": ""stripe"",
  ""purchaseBehavior"": {
    ""defaultPurchaseMethod"": ""stripeCheckout"",
    ""allowedPurchaseMethods"": [""stripeCheckout""],
    ""requireAgeVerificationForAdultContent"": true,
    ""allowEntertainmentLabeling"": true,
    ""minimumPurchaseMinor"": 100,
    ""maximumPurchaseMinor"": 250000
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 86
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/items/purchase\" on the \"stable\" ring as \"buyer" +
                        "\" with JSON:", "{\r\n  \"mediaItemId\": \"media-anna-adult-1\",\r\n  \"paymentMethod\": \"credits\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("the response status should be 409", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 94
    await testRunner.AndAsync("the response JSON at \"error\" should equal \"payment-method-not-allowed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
    await testRunner.WhenAsync("I send a \"POST\" request to \"/admin/plugins/config\" on the \"stable\" ring as \"admin" +
                        "\" with JSON:", @"{
  ""pluginId"": ""stripe"",
  ""purchaseBehavior"": {
    ""defaultPurchaseMethod"": ""credits"",
    ""allowedPurchaseMethods"": [""credits"", ""stripeCheckout""],
    ""requireAgeVerificationForAdultContent"": true,
    ""allowEntertainmentLabeling"": true,
    ""minimumPurchaseMinor"": 100,
    ""maximumPurchaseMinor"": 250000
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 112
    await testRunner.WhenAsync("I send a \"GET\" request to \"/account/wallet\" on the \"stable\" ring as \"buyer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 114
    await testRunner.AndAsync("the response JSON at \"wallet.creditsMinor\" should equal \"6500\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/items/purchase\" on the \"stable\" ring as \"buyer" +
                        "\" with JSON:", "{\r\n  \"mediaItemId\": \"media-anna-adult-1\",\r\n  \"paymentMethod\": \"credits\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
    await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 124
    await testRunner.AndAsync("the response JSON at \"purchase.status\" should equal \"completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.AndAsync("the response JSON at \"invoice.status\" should equal \"paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
    await testRunner.AndAsync("the response JSON at \"invoice.label\" should equal \"Leisure content value\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
    await testRunner.AndAsync("the response JSON at \"wallet.creditsMinor\" should equal \"4300\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
    await testRunner.WhenAsync("I send a \"GET\" request to \"/account/invoices\" on the \"stable\" ring as \"buyer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 130
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table18.AddRow(new string[] {
                            "label",
                            "Leisure content value"});
                table18.AddRow(new string[] {
                            "status",
                            "paid"});
                table18.AddRow(new string[] {
                            "totalMinor",
                            "2200"});
#line 131
    await testRunner.AndAsync("the response JSON array at \"invoices\" should contain an object with:", ((string)(null)), table18, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CommerceAndPaymentControlsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CommerceAndPaymentControlsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
