// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlyFling.Api.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PreviewAndCanaryEnrollmentFeature : object, global::Xunit.IClassFixture<PreviewAndCanaryEnrollmentFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Preview and canary enrollment", "  Stable and canary API rings should expose preview modules only for enrolled acc" +
                "ounts.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PreviewCanary.feature"
#line hidden
        
        public PreviewAndCanaryEnrollmentFeature(PreviewAndCanaryEnrollmentFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PreviewCanary.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Preview modules require enrollment and canary exposure")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Preview and canary enrollment")]
        [global::Xunit.TraitAttribute("Description", "Preview modules require enrollment and canary exposure")]
        public async global::System.Threading.Tasks.Task PreviewModulesRequireEnrollmentAndCanaryExposure()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preview modules require enrollment and canary exposure", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("I sign in on the \"stable\" ring as \"anna@example.com\" using device \"BDD Anna Previ" +
                        "ew\" and store it as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.WhenAsync("I send a \"GET\" request to \"/health\" on the \"stable\" ring", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
    await testRunner.AndAsync("the response JSON at \"deploymentRing\" should equal \"primary\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.WhenAsync("I send a \"GET\" request to \"/health\" on the \"canary\" ring", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("the response JSON at \"deploymentRing\" should equal \"canary\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.WhenAsync("I send a \"GET\" request to \"/connectors/modules\" on the \"stable\" ring as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table20.AddRow(new string[] {
                            "id",
                            "studio-preview"});
                table20.AddRow(new string[] {
                            "eligibility.allowed",
                            "true"});
                table20.AddRow(new string[] {
                            "eligibility.effectiveChannel",
                            "stable"});
                table20.AddRow(new string[] {
                            "eligibility.effectiveRoute",
                            "/studio/sessions"});
#line 17
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table20, "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table21.AddRow(new string[] {
                            "id",
                            "adult-platform-preview"});
                table21.AddRow(new string[] {
                            "eligibility.reason",
                            "preview-enrollment-required"});
#line 23
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table21, "And ");
#line hidden
#line 28
    await testRunner.WhenAsync("I send a \"POST\" request to \"/connectors/preview/enroll\" on the \"stable\" ring as \"" +
                        "anna\" with JSON:", "{\r\n  \"moduleId\": \"studio-preview\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
    await testRunner.WhenAsync("I send a \"POST\" request to \"/connectors/preview/enroll\" on the \"stable\" ring as \"" +
                        "anna\" with JSON:", "{\r\n  \"moduleId\": \"adult-platform-preview\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
    await testRunner.WhenAsync("I send a \"GET\" request to \"/connectors/modules\" on the \"stable\" ring as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table22.AddRow(new string[] {
                            "id",
                            "studio-preview"});
                table22.AddRow(new string[] {
                            "eligibility.effectiveChannel",
                            "stable"});
                table22.AddRow(new string[] {
                            "eligibility.effectiveRoute",
                            "/studio/sessions"});
#line 46
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table22, "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table23.AddRow(new string[] {
                            "id",
                            "adult-platform-preview"});
                table23.AddRow(new string[] {
                            "eligibility.allowed",
                            "false"});
                table23.AddRow(new string[] {
                            "eligibility.reason",
                            "canary-ring-required"});
#line 51
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table23, "And ");
#line hidden
#line 57
    await testRunner.WhenAsync("I send a \"GET\" request to \"/connectors/modules\" on the \"canary\" ring as \"anna\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table24.AddRow(new string[] {
                            "id",
                            "studio-preview"});
                table24.AddRow(new string[] {
                            "eligibility.allowed",
                            "true"});
                table24.AddRow(new string[] {
                            "eligibility.effectiveChannel",
                            "preview"});
                table24.AddRow(new string[] {
                            "eligibility.effectiveRoute",
                            "/studio/sessions?channel=preview"});
#line 59
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table24, "And ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table25.AddRow(new string[] {
                            "id",
                            "adult-platform-preview"});
                table25.AddRow(new string[] {
                            "eligibility.allowed",
                            "true"});
                table25.AddRow(new string[] {
                            "eligibility.effectiveChannel",
                            "preview"});
                table25.AddRow(new string[] {
                            "eligibility.effectiveRoute",
                            "/account/verification-readiness?channel=preview"});
#line 65
    await testRunner.AndAsync("the response JSON array at \"modules\" should contain an object with:", ((string)(null)), table25, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PreviewAndCanaryEnrollmentFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PreviewAndCanaryEnrollmentFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
