// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlyFling.Api.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UploadIntakeWithConsentAndPolicyCaptureFeature : object, global::Xunit.IClassFixture<UploadIntakeWithConsentAndPolicyCaptureFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Upload intake with consent and policy capture", "  Upload intake should preserve consent and policy artifacts before media transfe" +
                "r begins.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UploadIntake.feature"
#line hidden
        
        public UploadIntakeWithConsentAndPolicyCaptureFeature(UploadIntakeWithConsentAndPolicyCaptureFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UploadIntake.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Upload intake captures consent metadata and policy artifacts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Upload intake with consent and policy capture")]
        [global::Xunit.TraitAttribute("Description", "Upload intake captures consent metadata and policy artifacts")]
        public async global::System.Threading.Tasks.Task UploadIntakeCapturesConsentMetadataAndPolicyArtifacts()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload intake captures consent metadata and policy artifacts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("I sign in on the \"stable\" ring as \"bdd-uploader@example.com\" using device \"BDD Up" +
                        "load Browser\" and store it as \"uploader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/collections\" on the \"stable\" ring as \"uploader" +
                        "\" with JSON:", "{\r\n  \"folderName\": \"bdd-intake-folder\",\r\n  \"title\": \"BDD Intake Folder\",\r\n  \"desc" +
                        "ription\": \"Contract coverage for upload intake.\",\r\n  \"visibility\": \"private\",\r\n " +
                        " \"publishState\": \"draft\",\r\n  \"priceMinor\": 0,\r\n  \"currency\": \"GBP\"\r\n}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
    await testRunner.AndAsync("I save the response JSON at \"collection.id\" as \"uploadCollectionId\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.WhenAsync("I send a \"POST\" request to \"/media/uploads/intake\" on the \"stable\" ring as \"uploa" +
                        "der\" with JSON:", @"{
  ""collectionId"": ""{{uploadCollectionId}}"",
  ""title"": ""BDD Consent Image"",
  ""description"": ""Upload intake should keep policy and consent data together."",
  ""fileName"": ""consent-image.jpg"",
  ""contentType"": ""image/jpeg"",
  ""mediaType"": ""image"",
  ""ageRating"": ""general"",
  ""fileSizeBytes"": 4096,
  ""priceMinor"": 1500,
  ""currency"": ""GBP"",
  ""publishState"": ""draft"",
  ""encodingProfile"": {
    ""qualityProfile"": ""balanced"",
    ""bitrateProfile"": ""standard""
  },
  ""consent"": {
    ""performerCount"": 1,
    ""allAdultsConfirmed"": true,
    ""rightsConfirmed"": true,
    ""consentCapturedAt"": ""2026-05-01T10:15:00Z"",
    ""consentDocumentName"": ""bdd-consent-record"",
    ""recordRetentionYears"": 7,
    ""notes"": ""BDD captured consent proof.""
  },
  ""policy"": {
    ""folderName"": ""bdd-intake-folder"",
    ""documentName"": ""bdd-policy"",
    ""termsSummary"": ""Uploads require explicit adult confirmation, rights ownership, and moderation review before transfer completes."",
    ""pricingSummary"": ""Draft image will remain private until moderation and publish checks are complete."",
    ""additionalNotes"": ""BDD policy artifact coverage.""
  }
}", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("the response status should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("the response JSON at \"mediaItem.mediaType\" should equal \"image\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.AndAsync("the response JSON at \"mediaItem.uploadStatus\" should equal \"pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("the response JSON at \"mediaItem.consent.consentDocumentName\" should equal \"bdd-co" +
                        "nsent-record\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.AndAsync("the response JSON at \"mediaItem.storage.publicMetadata.identitySafe\" should equal" +
                        " \"true\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
    await testRunner.AndAsync("the response JSON at \"upload.mode\" should equal \"memory\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("the response JSON at \"upload.requiredHeaders.x-ms-blob-type\" should equal \"BlockB" +
                        "lob\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("I save the response JSON at \"mediaItem.id\" as \"uploadMediaItemId\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.AndAsync("I save the response JSON at \"mediaItem.policyArtifact.uri\" as \"policyArtifactUri\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
    await testRunner.AndAsync("the response body should not contain \"consent-image.jpg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
    await testRunner.AndAsync("the file at \"{{policyArtifactUri}}\" should contain \"BDD captured consent proof.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.AndAsync("the file at \"{{policyArtifactUri}}\" should contain \"All adults confirmed: yes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.AndAsync("the file at \"{{policyArtifactUri}}\" should contain \"BDD policy artifact coverage." +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.WhenAsync("I send a \"GET\" request to \"/media/uploads/events?limit=10\" on the \"stable\" ring a" +
                        "s \"uploader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table28.AddRow(new string[] {
                            "mediaItemId",
                            "{{uploadMediaItemId}}"});
                table28.AddRow(new string[] {
                            "status",
                            "pending"});
#line 75
    await testRunner.AndAsync("the response JSON array at \"events\" should contain an object with:", ((string)(null)), table28, "And ");
#line hidden
#line 80
    await testRunner.WhenAsync("I send a \"GET\" request to \"/media/uploads/queue\" on the \"stable\" ring as \"uploade" +
                        "r\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("the response status should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "path",
                            "value"});
                table29.AddRow(new string[] {
                            "mediaItemId",
                            "{{uploadMediaItemId}}"});
                table29.AddRow(new string[] {
                            "jobType",
                            "metadata-scrub"});
#line 82
    await testRunner.AndAsync("the response JSON array at \"workItems\" should contain an object with:", ((string)(null)), table29, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UploadIntakeWithConsentAndPolicyCaptureFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UploadIntakeWithConsentAndPolicyCaptureFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
